### PR TITLE
Remove unused plone profile

### LINKED ISSUE #55: Remove plone profile
It's not in use and a leftover from the bob template.

### PR DESCRIPTION
**Pull request by busykoala**
Close #55 

This pull removes the unused plone profile.

### CODE REVIEW

**Review by maethu — CHANGES_REQUESTED** [review]
I meant you could remove the whole profile. Currently we don't need any. 

Currently I don't have to `install` anything of this package, it just has to be in the sys path.

**Comment by busykoala** [comment]
@maethu, more something like that? I now removed all three directories and these from the configure.zcml. Not sure If I understood correctly though.

**Review by maethu — APPROVED** [review]
Nice ;-)

**Comment by busykoala** [comment]
@maethu, the tests were failing, because there were some tests regarding installing/ensuring/uninstalling the profile (also my linkchecker test installed the profile). I'm pretty sure I did the right thing, but could you check on the last commit anyway?

**Comment by maethu** [comment]
It does look good. But don't comment it out. Remove the actual line

**Pull request merged**
